# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PnacZ9QJhx6CHICPjq6fSNhS_Zoqk73I
"""

class Person: #Outer class
  def __init__(self):
    self.name='Debjit'
    self.dp=self.Dob()


  def display(self):
    print('name=',self.name)


  class Dob: #inner class
    def __init__(self):
      self.dd=10
      self.mm=5
      self.yy=2022

    def display(self):
      print('Dob={}/{}/{}'.format(self.dd,self.mm,self.yy))  


p=Person() #outer class object
p.display()


x=p.dp
x.display()

class Student1:
  def __init__(self):
    self.name='Swarnaly'

  def display(self):
    print('name= ', self.name)

  class Dob:

    def __init__ (self):
      self.dd=20
      self.mm=9
      self.yy=22

    def display(self):
      print('Dob={}/{}/{}'.format(self.dd,self.mm,self.yy))  


s=Student1()
s.display()

x=Student1().Dob()
x.display()

from teacher import Teacher

t=Teacher()
t.setid(23)
t.setname('Nitin')
t.setaddress('kolkata,mmg,700129')
t.setsalary('13000')




print('Id =',t.getid())
print('Name =',t.getname())
print('Address =',t.getaddress())
print('Salary=', t.getsalary())



from student import Student
st1=Student()

st1.setid(120)
print('studentid=',st1.getid() )

from teacher import Teacher
class Demo(Teacher):
  def setmarks(self, marks):
    self.marks=marks

  def getmarks(self):
    return self.marks 
  

de1=Demo()
de1.setid(200)
print('id=',de1.getid())