# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kgj70jA1uZB8fTnID5k-vsM_xphpL2sj
"""

class MyClass:
  name='boltu'
  roll=20

p1=MyClass()
p2=MyClass()
p3=MyClass()



print(p1.name, p1.roll,p3.roll )
#print(p2.name, p2.roll)
#print(p3.name, p3.roll)

class Student:
  def __init__(self, a, b):
    self.name=a
    self.roll=b


x=input("enter a value")
s1=Student(x,22)

print(s1.name)
print(s1.roll)

class Mota:
  def __init__(k, a,b):
    k.name=a
    k.weight=b

  def display(k):
    print("my name is ", k.name)  
    print("my weight is", k.weight)


m1=Mota('fatman',99) 
m1.display()