# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKy8wAeT3fH7y8ukiu1mn5wFfhFwVOcI
"""

class Student:
  def __init__(self,n='.',m=0):
    self.name=n
    self.marks=m

  def display(self):
    print('Hi', self.name)
    print('your marks',self.marks)



s=Student() #constructor is called without arguments
s.display()  

print('--------------------------------')

s1=Student('Laltu', 90)#constructor is called with two arguments
s1.display()

#Instance veriable

class Sample:
  def __init__(self): #constructor
    self.x=10

  def modify(self):   # instance method
    self.x+=2  


sam1=Sample()
sam2=Sample() 

print('x in sam1 is:',sam1.x)
print('x in sam2 is:',sam2.x)
print('-----------------------------------------------')
sam1.modify() # modify x in sam1
print('x in sam1 is:',sam1.x)
print('x in sam2 is:',sam2.x)

class Test: 
  x=10 # class veriable
  @classmethod
  def modify(cls): # class method
    cls.x+=2

te1=Test()
te2=Test()

print('x in te1 is', te1.x)
print('x in te2 is', te2.x)
print('-------------------------------------------')
te1.modify()
print('x in te1 is', te1.x)
print('x in te2 is', te2.x)