# -*- coding: utf-8 -*-
"""exception.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6pszGmXRSUWYmGRZLGY1rpGb00iEhVu
"""

#compile time error

x=1

if x==1
print('Gold is expensive')

x=1
if x==1:
  print('Old is gold')

x=10
if x%2==0:
  print(x,'is even number')
    print('x', is divisiable by 2)

#run-time error

def concat(a,b):
  print(a+b)

concat(5,'hello')

animal=['dog','cat','rat','monkey']
print(animal[4])

def increment(sal):
  sal=sal+(15*sal/100)
  return sal


newsalary=increment(40000) 
print('new salary is',newsalary)

p= int(input("enter a number"))
q=int(input('enter another number'))

print(p/q)

print('Hello boss')

try:
  f=open("myfile","w")
  a, b= [int(x) for x in input('Enter two numbers').split()]
  c=a/b
  f.write('writing %d into my file'%c)


except Exception as e:
  print('Divide by zero')
  print('Please do not enter 0 in input') 
  print("exception type is ",e) 

f.close()
print('file closed')