# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udN-C7HAvkdBdHatd-r0cDccY87cdycN
"""



"""Exception
ArithmaticError
AssertionError
AttributeError
EOFError
FloatingPointError
GeneratorExit
IOError
IndexError
ImportError
KeyError
KeyboardInterrupt
NameError
NotImplementedError
OverflowError
RuntimeError
StopIteration
SyntaxError
IndentationError
SystemExit
TypeError
UnboundLocalError
ValueError
ZeroDividionEror
"""

#example of syntax error

try:
  date=eval(input("Enter date:"))
except SyntaxError:
  print("Invalid date entered")

else:
  print("You entered date:",date) 

finally:
  print("Ajke amar mon valo nei")

try:
  name=input('Enter filename')
  f=open(name,'r')
except IOError:
  print('The  file is not found', name)
else:
  n=len(f.readlines()) 
  print(name,'has', n,'lines')
  f.close()

try:
  x=int(input("Enter a number between 5 and 10"))
  assert x>=5 and x<=10
  print("You entererd ", x)
except AssertionError:
  print('The condition is not fullfilled')

class MyException(Exception):
  def __init__(self, arg):
    self.arg=arg
  
def check(dict):
  for k,v in dict.items():
    print("Name={:15s} Balance={:10.2f}".format(k,v))
    if(v<2000.00):
      raise MyException('Balance amount  is less in the account of ' +k)



bank={'Raj':5000.00,'Boy':4000.00, 'Ajay':1950.00,'Puku':3000.00}
try:
  check(bank)
except MyException as me:
  print(me)