# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XIUr32mBJcxf2hrD7yCMnzVc_oCOGe-q
"""

class Father:
  def __init__(self):
    self.property=900000.00

  def display(self):
    print('Father \'s property :',self.property)

class Son(Father):
  pass


s=Son()
s.display()

class Mother:
  def __init__(self):
    self.myproperty=25000000.00

  def showProperty(self):
    print('mothers\' property is: ',self.myproperty)

class Daughter(Mother):
  def __init__(self):
    self.myproperty=10000.00
  def showProperty(self):
    print('child property is',self.myproperty)      



d=Daughter()
d.showProperty()
m=Mother()
m.showProperty()

class Husband:
  def __init__(self,hproperty=0.0):
    self.hproperty=hproperty

  def display_property(self):
    print('Husband\'s property is',self.hproperty) 

class Wife(Husband):
  def __init__(self, wproperty=0.0,hproperty=0.0):
    super().__init__(hproperty)
    self.wproperty=wproperty

  def  display_property(self):
    print('Total property of wife',self.hproperty + self.wproperty)

w=Wife(30000.00, 20000.00)
w.display_property()

3, 2, 11, 14, 27, 34

i=1
while(i<7):
  if i%2==0:
    print(i**2 -2)
  else:
    print(i**2 +2) 
  i+=1