# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFWfWBT2GL8yLSqRQtndbemesBR3l-R2
"""

class Swarnaly:
  age=99

s1=Swarnaly()
s2=Swarnaly()


print(s1.age)
print(s2.age)

class Baccha:
  def __init__(self,age):
    self.myage=age




b1=Baccha(22)
b2=Baccha(12)
b3=Baccha(77)

print(b1.myage)
print(b2.myage)
print(b3.myage)

class Kaccha:
  def __init__(bertho, roll, name):
    bertho.myname=name
    bertho.myroll=roll


ka1=Kaccha(10,'Somdutta')
ka2=Kaccha(11,'Debjit')


print(ka1.myroll)
print(ka1.myname)



print(ka2.myroll)
print(ka2.myname)

class pakka:
  def __init__(self, food, name):
    self.myname=name
    self.myfood=food


  def fun(self):
    print('my name is '+self.myname ) 
    print('I like '+self.myfood) 

p1=pakka('eggroll','Swarnaly') 
print(p1.myfood)
p1.myfood='ilsh'
p1.fun()

print(p1.myfood)

del p1

p1.fun()

name=input("Enter your name ")
age =int(input("Enter your age "))

print(name)
print(age)

print(type(age))

print(age+2)

a=min(23,34,78,4,7,8)

print(a)

b=max(23,34,78,4,7,8)
print(b)

c=pow(5,2)
print(c)

d=abs(-6.978)
print(d)

import math 
v=math.sqrt(25)
print(v)

f=math.ceil(3.9)
print(f)

g=math.floor(3.9)
print(g)

h=math.pi
print(h)