# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18f3cwb6s9cjhdBXXqNeZ6GePU6sB9XFS
"""

import numpy

arr=numpy.array([9,8,6,5,4])

print(arr)

print(type(arr))

print(numpy.__version__)

import numpy as np
arr1=np.array([23,45,67,89,21])
print(arr1)

import numpy as np #0D
arr2=np.array(56)
print(arr2)
print(arr2.ndim)

import numpy as np #1D
arr3=np.array([9,8,7,6,5,4,3,2,1])
print(arr3)
print(arr3.ndim)



import numpy as np #2D
app4=np.array([[1,2,3],[4,5,6]])

print(app4)
print(app4.ndim)

import numpy as np #3D
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

print(arr3d.ndim)

#1 dim access

print(arr3[3])
print(arr3[5])

print(arr3[3]+arr3[5])

#2 dim access
print(app4[1,1])

print(app4[0,0]+app4[1,2])

print(arr3d[1,0,2])