# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkzMP-OTH_O6UNGafuK_XIXVrANEpU_Y
"""

print('Name','Is','James',sep='$')

num= 8

print('%o'% num)

gold=5864.25684
print('%.2f' %gold)

swarnali=[]

for i in range(5):
  print("enter the value:")
  item=float(input())

  swarnali.append(item)



print('List: ', swarnali)

Polymorphism

a='swarnali'
b='bca'

c=a+b
print('c=',c)
d=20
e=45
f=d+e
print('f=',f)



class Duck:
  def talk(self):
    print('Quack quack !')

class Human:
  def talk(self):
    print('Hello, hi')


def callTalk(obj):
  obj.talk()    

x=Duck()
callTalk(x)

y=Human()
callTalk(y)

class BookX:
  def __init__(self, pages):
    self.pages=pages 
  def __sub__(self, others):
    return self.pages * others.pages

class BookY:
  def __init__(self, pages):
    self.pages=pages 


b1=BookX(200)
b2=BookY(100)


print(b1-b2)