# -*- coding: utf-8 -*-
"""staticmethod3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvxf2uQTD1m_UwaxZgDBXXTs5BhVyHhV
"""

import math

class Sample:
  @staticmethod
  def calculate(x):
    result= math.sqrt(x)
    return result


num=float(input('Enter a number: '))

res=Sample.calculate(num)
print('The square root if {} is {: .2f}'.format(num, res))

import sys
class Bank():
  
  def __init__(self, name, balance=0.0):
    self.name=name
    self.balance=balance

  def deposit(self, amount):
    self.balance+=amount
  

  def withdraw(self, amount):
    if amount>self.balance:
      print('Insufficient balance: ')
    else:
      self.balance-=amount
      return self.balance

name= input("Enter your name")

b=Bank(name)


while True:
  print('d- diposit, w-wiyhdraw, e-exit')
  choice=input('Enter your choice')
  if choice=='e' or choice=='E':
    sys.exit()

  amt=float(input('Enter amount:'))

  if choice=='d' or choice=='D':
    print("Balance after diposit",b.deposit(amt))

  elif choice=='w' or choice=='W': 
    print("Balance after withdral",b.withdraw(amt))

class Emp:
  def __init__(self,id, name , salary):
    self.id=id
    self.name=name
    self.salary=salary

  def display(self):
    print('Id=',self.id)
    print('Name=',self.name)
    print('Salary=',self.salary)


class Myclass:

  @staticmethod
  def mymethod(e):
    e.salary+=1000
    e.display()
      

e=Emp(20,'Ram',16000.50)

Myclass.mymethod(e)

class Demo:
  @staticmethod
  def mymethod(x,n):
    result=x**n
    print('{} to the power {} is {}'.format(x,n,result))


Demo.mymethod(4,2)
Demo.mymethod(5,3)