# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVXIdQD2xR2uhrg3wqwA5m0xEDyPgGgW
"""

name=' Swarnaly Bar'

name

print(name.lstrip()) # left space remove

print(name.rstrip()) #right space remove

str= input('Enter a string: ')
sub=input('Enter sub string: ')

n=str.find(sub,0,len(str))

if n==-1:
  print("The sub string not found",n)
else:
  print("The sub string is found at position", n+1)

str1='New Delhi Delhi Delhi'
n=str1.count('Delhi')

print(n)
print(len(str1))

n= str1.count('e',3,21)
print(n)

gold='swarnaly'

print(gold[5])
gold[5]='x'
print(gold)

s1='one'
s2='two'
print(id(s1))
print(id(s2))



print(s1)
print(s2)

s1='one'
s2='two'
s2=s1
print(s1)
print(s2)
s3='one'
print(s3)

print(id(s1))
print(id(s2))
print(id(s3))

str2='This is a beautiful girl'
s1='girl'
s2='flower'

str3=str2.replace(s1,s2)

print(str2)
print(str3)

str5='one, two, three, four'
str6=str5.split(',')
print(str6)

str= input(" Enter number separated by space: ")
lst=str.split(' ')

for i in lst:
  print(i)

print(lst)