# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15sjqo1FgOpplc7LD0uMZZAwDOEFK6iMd
"""

s1='I am a student'
s2="You are a boy"

print(s1)
print(s2)

s3=''' This is a sring'''

s4=""" I am in Kolakata"""

print(s3)
print(s4)

s5="I am \n Indian"
print(s5)

s6='city of \bjoy'
print(s6)

s7='india is a \t great country'
print(s7)

s8='india is a 3\\4 great country' #escape character
print(s8)

name=u'\u09C7\u09A6\u09AC'
print(name)

s10='madhyamgram city'
n=len(s10)
print(n)

i=0
while i<n:
  print(s10[i], end=" ")
  i=i+1

i=-1
while i>=-n:
  print(s10[i], end=" ")
  i=i-1

s11='madhyamgram rail'
for k in s10:
  print(k, end=' ')

for k in s10[::-1]:
  print(k, end=' ')

print(s11*2)

print(s11[7:12]*4)

str1="Partha"
str2="Arpita"
str3=str1+str2 #string concatinataion
print(str3)

str3=input('Enter a string:')
str4=input("Enter another string :")

if str4 in str3:
  print(str4 +' is found ')
else:
  print(str4 +' is not  found ')

st1='boo'
st2='bop'

if st1>st2:
  print('hello')
else:
  print('hi')

st1r1= '  debjit bar  '
print(st1r1)

st1r1

print(st1r1.strip())

st1r1.strip()